export async function fetchCars(filters) {
	const url = new URL("https://cars-by-api-ninjas.p.rapidapi.com/v1/cars/");
	url.searchParams.set("make", filters.manufacturer);
	url.searchParams.set("model", filters.model);
	url.searchParams.set("fuel", filters.fuel);
	url.searchParams.set("limit", filters.limit);
	url.searchParams.set("year", filters.year);
	console.log(`${url}`);
	// console.log(filters);
	// https://rapidapi.com/apininjas/api/cars-by-api-ninjas
	const headers = {
		"X-RapidAPI-Key": "5eed433d14msh7d6c484068c7a5fp1426f9jsn1249491a8059",
		"X-RapidAPI-Host": "cars-by-api-ninjas.p.rapidapi.com",
	};
	const response = await fetch(`${url}`, { headers: headers });
	const result = await response.json();
	// console.log(result);
	return result;
}

// generated by chat gpt
export function calculateRent(car) {
	let currentYear = new Date().getFullYear();
	let transmissionFactor = getTransmissionFactor(car.transmission);

	let rent = currentYear - car.year + car.city_mpg - transmissionFactor;
	return rent;
}

function getTransmissionFactor(transmission) {
	// Assign transmission factors based on transmission type
	if (transmission === "a") {
		return 5;
	} else if (transmission === "m") {
		return 2;
	} else {
		return 0; // Default factor if transmission type is not recognized
	}
}

// this functoin is using google custome search json api but it is not the optimal for getting car images
//insted use  https://imagin.studio/car-image-api but it needs a buissness email to get an api key
// so for now ill keep one image for all of the cars

// export const generateCarImageUrl = async () => {
// 	console.log("GOOGLE_API_KEY", process.env.GOOGLE_API_KEY);
// 	const response = await fetch(
// 		`https://www.googleapis.com/customsearch/v1?key=AIzaSyBRpXvBfIjVmQPhXxtJGA1sxTLN7RpyMVI&cx=943630a20a12f453b&q=bmw+car`
// 	);
// 	const data = response.json();
// 	return data;
// };

//note: to use the google custome search json api include head componenet at the root layout of the program
/**
 * import the Head component from next/head
 * <Head>
				{" "}
				<script
					async
					src="https://cse.google.com/cse.js?cx=943630a20a12f453b"
				></script>
			</Head>
 */

// i got a key from jsm youtube channel
//important note
/**
			 * in next.confing.js 
			 * add the following 
			 * images: {
		domains: ["cdn.imagin.studio"],
	},
			 * 
			 */
export const generateCarImageUrlImaginStudio = (car, angle = "0") => {
	const url = new URL("https:cdn.imagin.studio/getimage");
	const { make, year, model } = car;
	url.searchParams.append("customer", "hrjavascript-mastery");
	url.searchParams.append("make", make);
	url.searchParams.append("modelFamily", model.split("")[0]);
	url.searchParams.append("zoomType", "fullscreen");
	url.searchParams.append("modelYear", `${year}`);
	url.searchParams.append("angle", `${angle}`);
	// console.log(url);
	return `${url}`;
};

// reusable code to change the search parametes
export const updateSearchParams = (type, value) => {
	const searchParams = new URLSearchParams(window.location.search);
	searchParams.delete(type); // Remove existing parameter
	searchParams.set(type, value);
	const newPathName = `${window.location.pathname}?${searchParams.toString()}`;
	console.log("newPathName", newPathName);
	return newPathName;
};
